services:
  - type: web
    name: solar-enrollment-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn solar_enrollment.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: DATABASE_URL
        fromDatabase:
          name: solar-enrollment-db
          property: connectionString

databases:
  - name: solar-enrollment-db
