# Generated by Django 5.2.1 on 2025-06-01 18:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(default='NJ', max_length=2)),
                ('zip_code', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^\\d{5}$', 'Enter a valid 5-digit ZIP code')])),
                ('utility', models.CharField(choices=[('PSEG', 'PSE&G'), ('JCPL', 'Jersey Central Power & Light'), ('ACE', 'Atlantic City Electric')], max_length=10)),
                ('utility_account_number', models.CharField(blank=True, max_length=20)),
                ('assistance_program', models.CharField(blank=True, choices=[('Medicare', 'Medicare'), ('SNAP', 'SNAP'), ('', 'None')], max_length=20)),
                ('address_validated', models.BooleanField(default=False)),
                ('formatted_address', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'subscribers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UtilityZipCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(max_length=5, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('electric_utility', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Utility Zip Code',
                'verbose_name_plural': 'Utility Zip Codes',
                'db_table': 'utility_zip_codes',
            },
        ),
    ]
