# Generated by Django 5.2.1 on 2025-06-01 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='utility',
            field=models.CharField(choices=[('PSEG', 'PSE&G'), ('JCPL', 'Jersey Central Power & Light'), ('ACE', 'Atlantic City Electric'), ('ROCKLAND', 'Rockland Electric Co.')], max_length=10),
        ),
    ]
